setwd("C:/Users/Christian/datasciencecoursera/data_exploration")
library('dplyr')
library('datasets')
household_power_consumption <- read.csv("C:/Users/Christian/datasciencecoursera/data_exploration/household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE)
png(file='plot3.png', width = 480, height = 480, unit = 'px')
Global_active_power_sub <- transmute(household_power_consumption,Date1 = as.Date(Date, "%d/%m/%Y" ), Date = Date, Time = Time, Sub_metering_1 = as.numeric(Sub_metering_1), Sub_metering_2 = as.numeric(Sub_metering_2), Sub_metering_3 = as.numeric(Sub_metering_3))
Global_active_power_sub <- filter(Global_active_power_sub, Date1 >= "2007-02-01" & Date1 <= "2007-02-02")
with(Global_active_power_sub, plot(type = "l", as.POSIXct(strptime(paste(Global_active_power_sub$Date, Global_active_power_sub$Time),"%d/%m/%Y %H:%M:%S")), Sub_metering_1, ylab = 'Energy sub metering', xlab = '', col = 'black'))
lines(as.POSIXct(strptime(paste(Global_active_power_sub$Date, Global_active_power_sub$Time),"%d/%m/%Y %H:%M:%S")), Global_active_power_sub$Sub_metering_2, col ='red')
lines(as.POSIXct(strptime(paste(Global_active_power_sub$Date, Global_active_power_sub$Time),"%d/%m/%Y %H:%M:%S")), Global_active_power_sub$Sub_metering_3, col ='blue')
legend("topright", pch = '-', col = c('black', 'red', 'blue'), legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
dev.off()